version: "3.8"

services:
  server:
    image: vimal1026/backend:latest
    container_name: backend
    ports:
      - "8001:8001"

  client:
    image: vimal1026/frontend:latest
    container_name: frontend
    ports:
      - "5174:5174"
    depends_on:
      - server
